### ISSUE TITLE
exec command - Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by lovasoa** [openode-io/openode-cli#18]
Hello, 
  I am still seeing crashes in version 2.0.15

```
$ npx openode exec www ls
TypeError: Cannot read property 'replace' of undefined
    at normalizeApiUrl (/Users/olojkine/Developpement/whitebophir/node_modules/openode/modules/cliConfs.js:9:14)
    at Object.determineClosestEndpoint (/Users/olojkine/Developpement/whitebophir/node_modules/openode/modules/cliConfs.js:19:19)
    at async Object.prepareAuthenticatedCommand (/Users/olojkine/Developpement/whitebophir/node_modules/openode/modules/main.js:33:5)
    at async prepareAuth (/Users/olojkine/Developpement/whitebophir/node_modules/openode/index.js:38:17)
    at async Command.<anonymous> (/Users/olojkine/Developpement/whitebophir/node_modules/openode/index.js:316:27)
⠋ run command err
Error: Unable to process the location null
    at Object.locations2Process (/Users/olojkine/Developpement/whitebophir/node_modules/openode/modules/locations.js:41:11)
    at async processAllLocations (/Users/olojkine/Developpement/whitebophir/node_modules/openode/index.js:56:25)
    at async progress (/Users/olojkine/Developpement/whitebophir/node_modules/openode/index.js:656:16)
    at async runCommand (/Users/olojkine/Developpement/whitebophir/node_modules/openode/index.js:20:18)
    at async Command.<anonymous> (/Users/olojkine/Developpement/whitebophir/node_modules/openode/index.js:333:9)
```

**Comment by martinlevesque** [comment]
does not seem to occur anymore, please reopen if it still occur
